### ISSUE TITLE
Sensor Detected Incorrectly

### ISSUE THREAD

**Issue by Sergeant-Steve** [PlusPlus-ua/ha_mobilealerts#1]
I have an MA10320 sensor which is being detected as MA10120, so it thinks the External Temperature Probe is at 71C while the Humidity is Unknown. In fact it is the other way around, the Humidity is 71% but the external temperature is unknown as the probe is not connected.

Sensor Type MA10120 is only temperature, so if Humidity is present it must be MA10320 type sensor.

![Mobile Alerts Sensor Incorrect Detection Type](https://user-images.githubusercontent.com/43524510/192183371-64c30a33-82fc-442b-ae41-af1cc4edf0e7.JPG)
![Screenshot of Mobile Alerts App Showing Sensor MA10320](https://user-images.githubusercontent.com/43524510/192184418-96c37a48-34f4-4e3e-8770-6e888e84a7ab.png)

**Comment by PlusPlus-ua** [comment]
Thank you for feedback. I've fixed the problem. Could you please check it.

**Comment by Sergeant-Steve** [comment]
Changes made have fixed the issue. Humidity is now being displayed correctly.
